version : '3.8'
services :
  seedon :
    image: seedon:latest
    container_name: seedon_tanda
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - no-internet
      - internet
    environment:
      - SPRING_DATASOURCE_IP=192.168.0.130
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DATABASE=SeedOnTanda
      - SPRING_DATASOURCE_USERNAME=amigoscode
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 8080:8080

  kafka:
    image: confluentinc/cp-kafka:latest
    external_links:
      - docker-kafka-1

networks:
  no-internet:
    external: true
  internet:
    external: true




