version : '3.8'
services :
  seedon :
    image: seedon:latest
    container_name: seedon_tanda
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - no-internet
      - internet
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.0.130:5432/SeedOnTanda
      - SPRING_DATASOURCE_USERNAME=amigoscode
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_FLYWAY_URL=jdbc:postgresql://192.168.0.130:5432/SeedOnTanda
      - SPRING_FLYWAY_USER=amigoscode
      - SPRING_FLYWAY_PASSWORD=password
      - SPRING_KAFKA_SERVER=localhost:29092
    ports:
      - 8080:8080

  kafka:
    image: confluentinc/cp-kafka:latest
    external_links:
      - docker-kafka-1

networks:
  no-internet:
    external: true
  internet:
    external: true




